<?php

/**
 * @file
 * Contains HELfi demo module hooks etc.
 */

declare(strict_types=1);

/**
 * Implements hook_config_ignore_settings_alter().
 */
function helfi_demo_config_ignore_settings_alter(array &$settings) {
  // Chatleijuke is used in hammashoito chat in Sote.
  // Genesyschat might be used in palvelukeskus later but
  // the block configs already removed from other instances.
  $add_ignore = [
    'block.block.hdbt_teliaacewidget*',
    'block.block.hdbt_teliaacedemo*',
    'block.block.teliaacedemo*',
  ];

  foreach ($add_ignore as $config) {
    if (in_array($config, $settings)) {
      continue;
    }
    array_push($settings, $config);
  }
}
