_core:
  default_config_hash: NGxFi-xycxrzrGVZtCUl7MACi0jVRk130tNabvIN6ng
content_root: ''
assertiveness: smart
no_load: ''
embedded_content_warning: ''
download_links: ''
ignore_link_strings: ''
hidden_handlers: ''
ck5_table_headers: row
ignore_containers: ''
allow_overflow: ''
