_core:
  default_config_hash: avLbUotYjwF8ufc-mo2Awowg5lkVztiWg26H7YNn7eE
langcode: en
site_settings:
  theme_color: coat-of-arms
  default_icon: home-smoke
  koro: basic
footer_settings:
  footer_color: dark
